"""followers

Revision ID: 93089003a43c
Revises: 8b3c922ac549
Create Date: 2019-07-07 14:20:46.482952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93089003a43c'
down_revision = '8b3c922ac549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
